name: CI - IPL Predictor

on:
  push:
    branches: [ main ]  # run on every push to main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # run on a GitHub-hosted Linux server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run a basic test (optional)
      run: echo "✅ CI Workflow ran successfully"
